### ISSUE TITLE
gulp tasks npm gulp build fails

### ISSUE THREAD

**Issue by apamwach** [cssninjaStudio/krypton#6]
**issue definition**
As instructed after cloning the repo,  and updating packages after running npm install everything works fine untill the next step where npm gulp build squarks 

**Expected behaviour**
npm gulp build runs successfully.
**Actual behaviour**
Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/$user/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.9.0 /home/$user/.nvm/versions/node/v10.15.3/lib/node_modules/npm

Did you mean one of these?
    up
    help

**steps to reproduce**
1. Clone the repo
2. cd into the root directory
3. run npm install
  at first it will squark untill you update some puckages namely gulp-sass and related ones
4. run npm gulp build

**Comment by m-fin** [comment]
I'm getting this same error. Has anyone figured this out?
